on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Dm Cuoc Doi
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install doctl
        uses: bizflycloud/action-bizflyctl@v0.14
        id: hello
        with:
          version:  "v0.2.1"
          email: ${{ secrets.BIZFLYCLOUD_EMAIL }}
          password: ${{ secrets.BIZFLYCLOUD_PASSWORD }}
      - name: Run bizflyctl
        run: bizfly server list
        env:
          email: ${{ secrets.BIZFLYCLOUD_EMAIL }}
          password: ${{ secrets.BIZFLYCLOUD_PASSWORD }}