on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install doctl
        uses: bizflycloud/action-bizflyctl@v1.0
        id: hello
        with:
          email: ${{ secrets.BIZFLYCLOUD_EMAIL }}
          password: ${{ secrets.BIZFLYCLOUD_PASSWORD }}
      - name: Run bizflyctl
        run: bizflyctl server list