on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Dm Cuoc Doi
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install doctl
        uses: bizflycloud/action-bizflyctl@v0.9
        id: hello
        with:
          version:  "v0.2.1"
        env:
          BIZFLY_CLOUD_EMAIL: ${{ secrets.BIZFLYCLOUD_EMAIL }}
          BIZFLY_CLOUD_PASSWORD: ${{ secrets.BIZFLYCLOUD_PASSWORD }}
      - name: echo
        run: echo ${{ env.BIZFLY_CLOUD_EMAIL }}
      - name: echo2
        run: echo ${ env.BIZFLY_CLOUD_PASSWORD }
      - name: Run bizflyctl
        run: bizfly server list